version: '3.9'

services:
  devtiro:
    container_name: new_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
       POSTGRES_USERNAME: postgres
       POSTGRES_PASSWORD: root123
       POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

